const prefix = '/admin'

export default {
  // 网站统计网站概况
  statisticsFlowOverview: `${prefix}/statisticsflow/overview`,
  // 趋势分析-图表数据
  statisticsImage: `${prefix}/statisticsflow/image`,
  // 今日访客
  statisticsvisitTimeuser: `${prefix}/statisticsvisit/timeuser`,
  // 访客数据
  statisticsvisitUser: `${prefix}/statisticsvisit/user`,
  // 来源网站
  statisticsSourceSourceUrl: `${prefix}/statisticsSource/sourceUrl`,
  // 入口页面
  statisticsAccessPageEntrancePage: `${prefix}/statisticsAccessPage/entrancePage`,
  // 访问页面
  statisticsAccessPageAccessPage: `${prefix}/statisticsAccessPage/accessPage`,
  // 今天地域分布
  statisticsvisitTimearea: `${prefix}/statisticsvisit/timearea`,
  // 地域分布
  statisticsvisitArea: `${prefix}/statisticsvisit/area`,
  // 网站概述新老客户
  statisticsvisitSummarize: `${prefix}/statisticsvisit/summarize`,
  // 网站概述地域分布
  statisticsvisitSummarizeArea: `${prefix}/statisticsvisit/summarizeArea`,
  // 实时访客图表数据
  statisticsflowRealtime: `${prefix}/statisticsflow/realtime`,
  // 实时访客图表数据
  statisticsflowRealtimePage: `${prefix}/statisticsflow/realtime/page`,
  // 来源网站分页
  statisticsSourceSourceUrlPage: `${prefix}/statisticsSource/sourceUrl/page`,
  // 趋势分析-列表数据
  statisticsflowPage: `${prefix}/statisticsflow/page`,
  // 来源分析-来源类型
  statisticsSourceType: `${prefix}/statisticsSource/sourceType`,
  // 来源分析-来源网站分页
  statisticsSourceUrlPage: `${prefix}/statisticsSource/sourceUrl/page`,
  // 来源分析-搜索引擎
  statisticsSourceSearchEngine: `${prefix}/statisticsSource/searchEngine`,
  // 来源分析-外部链接（域名）
  statisticsSourceDomain: `${prefix}/statisticsSource/domain`,
  // 来源分析-外部链接（url）
  statisticsSourceUrl: `${prefix}/statisticsSource/url`,
  // 来源分析-外部链接（域名）分页
  statisticsSourceDomainPage: `${prefix}/statisticsSource/domain/page`,
  // 来源分析-外部链接（url）分页
  statisticsSourceUrlOuterPage: `${prefix}/statisticsSource/url/page`,
  // 地域分布-今天列表分页
  statisticsvisitTimepage: `${prefix}/statisticsvisit/timepage`,
  // 地域分布-日常列表分页
  statisticsvisitAreapage: `${prefix}/statisticsvisit/areapage`,
  // 今日设备-图表信息
  statisticsdeviceTimedevice: `${prefix}/statisticsdevice/timedevice`,
  // 今日设备-列表信息
  statisticsdeviceTime: `${prefix}/statisticsdevice/time`,
  // 今日设备-日常图表信息
  statisticsdeviceDevice: `${prefix}/statisticsdevice/device`,
  // 今日设备-日常列表信息
  statisticsdeviceDevices: `${prefix}/statisticsdevice/devices`,
  // 忠诚度-今日访问次数
  statisticsaccessTimePage: `${prefix}/statisticsaccess/timePage`,
  // 忠诚度-访问次数
  statisticsaccessPageInfo: `${prefix}/statisticsaccess/pageInfo`,
  // 忠诚度-今日访问深度
  statisticsaccessTimeHigh: `${prefix}/statisticsaccess/timeHigh`,
  // 忠诚度-访问深度
  statisticsaccessHighInfo: `${prefix}/statisticsaccess/highInfo`,
  // 忠诚度-今日访问时长
  statisticsaccessTime: `${prefix}/statisticsaccess/time`,
  // 忠诚度-访问时长
  statisticsaccessTimeInfo: `${prefix}/statisticsaccess/timeInfo`,
  // 实时访客-在线访问人数
  statisticsflowRealtimeUvnum: `${prefix}/statisticsflow/realtime/uvnum`
}
